import crypto from 'crypto'

export type ProvenanceMetadata = {
  id: string
  timestamp: string
  authority: string
  sourceThread: string
  destination: string
}

export function generateProvenanceId(): string {
  const now = new Date()
  const yy = String(now.getFullYear()).slice(2)
  const mm = String(now.getMonth() + 1).padStart(2, '0')
  const dd = String(now.getDate()).padStart(2, '0')
  const suffix = crypto.randomUUID().replace(/-/g, '').slice(0, 8).toUpperCase()
  return `TID-${yy}${mm}${dd}-${suffix}`
}

export function buildProvenance(opts: {
  destination: string
  sourceThread: string
  authority?: string
}): ProvenanceMetadata {
  return {
    id: generateProvenanceId(),
    timestamp: new Date().toISOString(),
    authority: opts.authority ?? 'Jon Hartman',
    sourceThread: opts.sourceThread,
    destination: opts.destination,
  }
}

export function formatProvenanceBlock(p: ProvenanceMetadata): string {
  const d = new Date(p.timestamp)
  const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
  const hrs = d.getHours()
  const h = hrs % 12 || 12
  const min = d.getMinutes().toString().padStart(2, '0')
  const ampm = hrs >= 12 ? 'P' : 'A'
  const mo = d.getMonth() + 1
  const dt = d.getDate()
  const yr = String(d.getFullYear()).slice(2)
  const label = `${days[d.getDay()]} ${h}:${min}${ampm} ${mo}/${dt}/${yr}`
  return [
    `Updated: ${label}`,
    `Generated By: TELA Runtime`,
    `Authority: ${p.authority}`,
    `Source Thread: ${p.sourceThread}`,
    `Destination: ${p.destination}`,
    `Provenance: ${p.id}`,
  ].join('\n')
}
